export const Languages = [
    'Javascript',
    'Typescript',
    'Java',
    'Python',
    'C',
    'C++',
    'C#',
    'SQL',
    'PHP',
    'Ruby',
    'Swift',
    'Objective-C',
    'Kotlin',
    'HTML',
    'CSS',
    'Golang',
    'Perl',
    'Rust',
    'R'
]

export const Skills = [
    'React',
    'Node.js',
    'MongoDB',
    'Express.js',
    'Angular',
    'AngularJS',
    'Next.js',
    'Flask',
    'Django',
    'Spring Boot',
    'Svelte',
    'Vue.js',
    'jQuery',
    'Ember.js',
    'Backbone',
    'Semantic-UI',
    'Foundation',
    'Preact',
    'ASP.NET Core',
    'Laravel',
    'Ruby on Rails',
    'Cake PHP',
    'Koa',
    'Phoenix',
    'AWS',
    'Azure',
    'GCP',
    'Firebase',
    'Nest.js',
    'Docker',
    'Kubernetes',
    'iOS',
    'Android',
    '.NET',
    'Maven',
    'JUnit',
    'Jest',
    'React Native',
    'Redux',
    'Redis',
    'Pandas',
    'Hibernate',
    'Selenium',
    'VSCode',
    'REST APIs',
    'CI/CD',
    'GraphQL',
    'PostgreSQL',
]